import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Land lord</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        <li>
          <Link
            href={{
              pathname: "/login",
            }}
          >
            <a>Login</a>
          </Link>
        </li>

        <li>
          <Link
            href={{
              pathname: "/register",
            }}
          >
            <a>Register</a>
          </Link>
        </li>

        <li>
          <Link
            href={{
              pathname: "/dashboard",
            }}
          >
            <a>dashboard</a>
          </Link>
        </li>
      </ul>
    </>
  );
};

export default Home;
