import type {NextPage} from "next";
import Head from "next/head";

const Home: NextPage = () => {

    return (
        <>
            <Head>
                <title>Land lord</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div className="container mx-auto my-auto h-screen flex align-center justify-center">

                <div className="my-auto">
                    <input type="text" className="input w-full max-w-xs block mb-3"  placeholder="email"/>

                    <input type="text" className="input w-full max-w-xs block mb-3"  placeholder="password"/>

                    <div className="w-full flex justify-end">
                        <button className="btn">Login</button>
                    </div>


                </div>
            </div>

        </>
    );
};

export default Home;


